formulae:
  - autoenv
  - coreutils
  - dbt-labs/dbt/dbt-bigquery
  - docker-compose
  - fnm
  - fzf
  - git
  - heroku/brew/heroku
  - jq
  - openjdk
  - postgresql@14
  - protobuf
  - s3cmd
  - spacelift-io/spacelift/spacectl
  - starship
  - terraform
  - tree
  - vips
  - wget
  - yarn
taps:
  - dbt-labs/dbt
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/core
  - spacelift-io/spacelift
casks:
  - 1password
  - docker
  - firefox-developer-edition
  - font-sauce-code-pro-nerd-font
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - linear-linear
  - loom
  - postico
  - postman
  - raycast
  - rectangle
  - slack
  - spotify
  - visual-studio-code
