formulae:
  - autoenv
  - coreutils
  - dbt-labs/dbt/dbt-bigquery
  - docker-compose
  - ffmpeg
  - fnm
  - fzf
  - gh
  - git
  - heroku/brew/heroku
  - incident-io/taps/catalog-importer
  - jq
  - openjdk
  - postgresql@14
  - protobuf
  - s3cmd
  - spacelift-io/spacelift/spacectl
  - starship
  - terraform
  - tree
  - vips
  - wget
  - yarn
taps:
  - dbt-labs/dbt
  - heroku/brew
  - homebrew/bundle
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - incident-io/homebrew-taps
  - spacelift-io/spacelift
casks:
  - 1password
  - docker
  - firefox-developer-edition
  - font-lato
  - font-noto-sans
  - font-open-sans
  - font-sauce-code-pro-nerd-font
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - linear-linear
  - loom
  - postico
  - postman
  - raycast
  - rectangle
  - slack
  - spotify
  - todoist
  - vlc
  - visual-studio-code
