#!/bin/bash

# Immediately stop script if a single commands fails.
set -e

function createDotfileSymlinks {
  ln -sf ~/projects/code/github.com/revett/dev-env/dotfiles/.gitconfig ~/.gitconfig
  ln -sf ~/projects/code/github.com/revett/dev-env/dotfiles/.zshrc ~/.zshrc
}

function generateGithubURL {
  git config remote.origin.url | cut -f2 -d. | tr ':' /
}

function generatePassword {
  dd if=/dev/urandom bs=1 count=30 2>/dev/null | base64
}

function listCommands {
  printf "Usage: alan <cmd> <args...>\n\n"
  printf "Commands:\n"
  printf " - gh-o\n"
  printf " - gh-pr\n"
  printf " - init\n"
  printf " - ls\n"
  printf " - pwd\n"
}

function openGithubPR {
  open https://github.$(generateGithubURL)/compare/$(git rev-parse --abbrev-ref HEAD)?expand=1
}

function openGithubURL {
  open https://github.$(generateGithubURL)
}

function outputError {
  printf "\e[31;4mERROR\e[0m: $1\n"
  exit 1
}

if [ "$#" -lt 1 ]; then
  listCommands
  exit 1
fi

case $1 in
  "gh-o") openGithubURL;;
  "gh-pr") openGithubPR;;
  "init") createDotfileSymlinks;;
  "ls") listCommands;;
  "pwd") generatePassword;;
  *) outputError "'$1' command not recognised.";;
esac
