#!/bin/sh

RED="\033[0;31m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
NC="\033[0m"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

commands ()
{
  echo "${PURPLE}Commands:${NC}\n" \
       "  ${BLUE}edit${NC}    - open vim for dev-env\n" \
       "  ${BLUE}list${NC}    - show known scripts\n" \
       "  ${BLUE}refresh${NC} - git pull new commits\n" \
       "  ${BLUE}setup${NC}   - initial setup";
}

not_found ()
{
  echo "${RED}'$1' is not a known command.${NC}\n"
  usage
  commands
  exit 1
}

usage ()
{
  echo "${PURPLE}Usage:${NC} anna <command>\n"
}

if [ $# -eq 0 ]; then
  commands
  exit 0
fi

if [ $# -gt 1 ]; then
  usage
  commands
  exit 1
fi

# Has single argument (guard statements above)
if [ -e $DIR/commands/$1 ];then
  source $DIR/commands/$1
  exit 0
else
  not_found $1
fi
