#!/bin/sh

RED="\033[0;31m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
NC="\033[0m"

commands ()
{
  echo "${PURPLE}Commands:${NC}\n" \
       "  ${BLUE}edit${NC}    - change how anna works\n" \
       "  ${BLUE}list${NC}    - show known scripts\n" \
       "  ${BLUE}refresh${NC} - git pull new commits\n" \
       "  ${BLUE}setup${NC}   - initial setup for anna";
}

not_found ()
{
  echo "${RED}'$1' is not a known command.${NC}\n"
  usage
  commands
  exit 1
}

setup ()
{
  if [ $(PWD) = "/Users/charlie/Dropbox/Projects/Code/Github/scripts" ]; then
    echo "Symlinking the directory..."
    ln -s ~/Dropbox/Projects/Code/Github/scripts ~/.scripts
    echo "Symlinking .zshrc to home..."
    ln -s ~/.scripts/dotfiles/.zshrc ~/.zshrc 
    exit 0
  else
    echo "${RED}Error: you must be in the scripts Dropbox directory to run this command.${NC}"
    exit 1
  fi  
}

usage ()
{
  echo "${PURPLE}Usage:${NC} anna <command>\n"
}

if [ $# -eq 0 ]; then
  commands
  exit 0
fi

if [ $# -gt 1 ]; then
  usage
  commands
  exit 1
fi

if [ $1 = "edit" ]; then
  vim ~/.scripts/anna 
  exit 0
fi

if [ $1 = "list" ]; then
  for file in ~/.scripts/commands/*
  do
    $(basename $file)
  done
  exit 0
fi

if [ $1 = "refresh" ]; then
  cd ~/.scripts
  git pull
  exit 0
fi

if [ $1 = "setup" ]; then
  setup
  exit 0
fi

not_found $1
