# OpenVPN Container
#
# Usage:
# OPENVPN_DOCKER_IMAGE=foo/bar OPENVPN_PROVIDER=foo OPENVPN_USERNAME=foo OPENVPN_PASSWORD=foo OPENVPN_VOLUME_PATH="~/path/to/foo" docker-compose up -d

version: "3.9"
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - "${OPENVPN_VOLUME_PATH}:/data"
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - NORDVPN_COUNTRY=GB
      - NORDVPN_CATEGORY=P2P
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    image: ${OPENVPN_DOCKER_IMAGE}
