font-family = "SauceCodePro Nerd Font Mono"
font-size = 12
theme = "GitHub Dark"

# Needed for cursor style to be applied correctly.
shell-integration-features = "no-cursor"
cursor-style = "block"

window-padding-x = 12
window-padding-y = 12
