# Configuration

font-family = "SauceCodePro Nerd Font Mono"
font-size = 14
theme = "GitHub-Dark-Default"

# Needed for cursor style to be applied correctly
shell-integration-features = "no-cursor"
cursor-style = "block"

window-padding-x = 12
window-padding-y = 12

window-inherit-working-directory = false
working-directory = "/Users/revett/projects/github.com"

# Keybindings

keybind = cmd+r=clear_screen
keybind = cmd+shift+r=reset
