# See: https://starship.rs/config

# ---
# General Configuration
# ---

add_newline = true
command_timeout = 750

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

# ---
# Disable Modules
# ---

[package]
disabled = true

# ---
# Configure Modules
# ---

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'
style = "white"
symbol = ""

[bun]
format = "[bun-v$version](white) "
version_format = "${raw}"

[cmd_duration]
format = "[$duration](yellow)"
min_time = 250

[directory]
style = "cyan"
truncate_to_repo = false

[git_branch]
style = "purple"
symbol = ""
truncation_length = 36
truncation_symbol = ""

[golang]
format = "[go-v$version](white) "
version_format = "${raw}"

[nodejs]
format = "[node-v$version](white) "
version_format = "${raw}"
