version: "3.4"
services:
  # DNS
  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - archivebox
      - uptime-kuma
      - miniflux
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  # Services
  archivebox:
    image: archivebox/archivebox:latest
    container_name: archivebox
    command: server --quick-init 0.0.0.0:8000
    environment:
      - PUBLIC_INDEX=False
      - PUBLIC_SNAPSHOTS=False
      - BASE_URL=https://archive.revcd.com
    volumes:
      - ../archivebox:/data
  miniflux:
    image: ghcr.io/miniflux/miniflux:latest
    container_name: miniflux
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    environment:
      - DATABASE_URL=${REVCD_MINIFLUX_DATABASE_URL}
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${REVCD_MINIFLUX_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${REVCD_MINIFLUX_ADMIN_PASSWORD}
      - BASE_URL=https://rss.revcd.com
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    environment:
      - BASE_URL=https://uptime.revcd.com
    volumes:
      - ../uptime-kuma:/app/data"

  # Utilities
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    command: --notifications "slack" --notification-slack-hook-url ${REVCD_WATCHTOWER_SLACK_URL} --schedule "0 0 4 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  caddy_data:
  caddy_config:
