version: "3.4"
services:
  # DNS
  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - uptime-kuma
      - miniflux
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  # Services
  miniflux:
    image: ghcr.io/miniflux/miniflux:latest
    container_name: miniflux
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    environment:
      - DATABASE_URL=${REVCD_MINIFLUX_DATABASE_URL}
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${REVCD_MINIFLUX_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${REVCD_MINIFLUX_ADMIN_PASSWORD}
      - BASE_URL=https://rss.revcd.com
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - BASE_URL=https://status.revcd.com
    volumes:
      - uptime-kuma:/app/data

  # Utilities
  logspout:
    image: gliderlabs/logspout:latest
    container_name: logspout
    restart: unless-stopped
    command: "syslog+tls://${REVCD_PAPERTRAIL_LOG_DESTINATION}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --notifications "slack" --notification-slack-hook-url ${REVCD_WATCHTOWER_SLACK_URL} --schedule "0 0 4 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  caddy_data:
  caddy_config:
  uptime-kuma:
    driver: local
