#!/bin/sh

USAGE="cosmos-ip <component> <env>"

if [ $# -eq 0 ]; then
  echo $USAGE
  exit 0
fi

if [ $# -ne 2 ]; then
  echo $USAGE
  exit 1
fi

echo "Component:   $1"
echo "Environment: $2"

IFS=' ' read -a array <<< $(bbc-cosmos-tools component ssh $1 --env=$2)
IP=${array[${#array[@]} - 1]}

echo "IP Address:  $IP"
echo ""

ssh $IP
