#!/bin/sh

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo "Symlinking .zshrc to $HOME..."
ln -s $DIR/../dotfiles/.zshrc ~/.zshrc

echo "Symlinking .vimrc to $HOME..."
ln -s $DIR/../dotfiles/.vimrc ~/.vimrc

echo "Symlinking .vim/ to $HOME..."
ln -s $DIR/../dotfiles/.vim ~/.vim

# Thoughts:
# - gives option to delete file if already exists
# - use for loop
