#!/bin/sh

BLUE="\033[0;34m"
RED="\033[0;31m"
PURPLE="\033[0;35m"
NC="\033[0m"

usage ()
{
  echo "${BLUE}multi-config-push${NC}\n" \
       "  - push config to multiple Cosmos components.\n" \
       "  - ${PURPLE}args:${NC} <comp_1...comp_n> <project> <env>";
}

if [ $# -eq 0 ]; then
  usage
  exit 0
fi

if [ $# -lt 3 ]; then
  echo "${RED}ERROR${NC} - must give at least 3 arguments."
  usage
  exit 1
fi

COMPONENTS=( "$@" )

ENV=${COMPONENTS[${#COMPONENTS[@]} - 1]}
unset COMPONENTS[${#COMPONENTS[@]}-1]

PROJECT=${COMPONENTS[${#COMPONENTS[@]} - 1]}
unset COMPONENTS[${#COMPONENTS[@]}-1]

echo "Components:  ${COMPONENTS[@]}"
echo "Project:     $PROJECT"
echo "Environment: $ENV"
echo

read -p "Are you sure (y/n)? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  echo "Okay! Stopping."
  exit 1
fi

for component in "${COMPONENTS[@]}"; do
  bbc-cosmos-tools config push $component --project=$PROJECT --env=$ENV --force;
done
