#!/bin/sh

BLUE="\033[0;34m"
RED="\033[0;31m"
PURPLE="\033[0;35m"
NC="\033[0m"

usage ()
{
  echo "${BLUE}cosmos-ip${NC}\n" \
       "  - login to a Cosmos component.\n" \
       "  - ${PURPLE}args:${NC} <component> <env>";
}

if [ $# -eq 0 ]; then
  usage
  exit 0
fi

if [ $# -ne 2 ]; then
  echo "${RED}ERROR${NC} - must give 2 arguments."
  usage
  exit 1
fi

echo "Component:   $1"
echo "Environment: $2"

bbc-cosmos-tools release redeploy $1 --env=$2
